root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
  bin = "./tmp/main.exe"
  include_ext = ["go", "tmpl", "tpl", "html"]
  exclude_dir = ["tmp", "vendor", "migrations", "templates"]
  exclude_regex = ["_test.go"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 2000

[misc]
  clean_on_exit = true

[log]
  time = true
